### ISSUE TITLE
Test are down again

### ISSUE THREAD

**Issue by adam3smith** [zotero/provo#7]
no tests for the last four days. @simonster could you take a look?

**Comment by dstillman** [comment]
Gecko tests are back:

https://zotero-translator-tests.s3.amazonaws.com/index.html

(They haven't really been down since 2014, but looks like they haven't been running since June 2015.)

Still working on getting this running automatically again, and for all the platforms, but we now have an up-to-date full run.

/cc @zuphilip

**Comment by adam3smith** [comment]
cc @mvolz

**Comment by zuphilip** [comment]
Great to see this!

@dstillman The translators does not seem to be up-to-date; because the first testcase (3news.co.nz) was renamed updated in the last days: https://github.com/zotero/translators/commit/be698f90b0cf0b673f31595ee97ad55c94a8c5c6

**Comment by dstillman** [comment]
@zuphilip: Should be fixed for the next run.

translation-server tests are also up, and [it isn't pretty](https://github.com/zotero/translation-server/issues/36). I'll see what I can do.

**Comment by zuphilip** [comment]
@dstillman Neither the gecko tests nor the server tests seems to be running the last days. Any fix would be appreciated...

**Comment by dstillman** [comment]
Gecko and Server tests from today are up.
