### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by adam3smith** [zotero/provo#8]
Trying to run this locally, I get
`./test.sh: line 84:  9908 Segmentation fault      (core dumped) "$APP_DIRECTORY/zotero" -profile "$FIREFOX_PROFILE_DIRECTORY" -provooutputdir "$OUTPUT_DIRECTORY" -provopayloaddir "$BOOKMARKLET_PAYLOAD_DIRECTORY" $provorun -provosuffix "$SUFFIX"
`
I think I have everything running correctly & am only trying to run gecko tests.

**Comment by simonster** [comment]
The segfault is happening because Mozilla broke XULRunner on Linux and I still have to adjust zotero-standalone-build to use Firefox instead. You might be able to work around it for now by setting zotero-standalone-build to use Gecko 39 and then re-running `fetch_xulrunner.sh`.

In case you don't already know, the less automated version of this is to go to `chrome://zotero/content/tools/testTranslators/testTranslators.html` in Firefox.

**Comment by adam3smith** [comment]
I did not know about the less automated version, which does all I need locally, so thanks for that! 
Not going to bother trying to fix the build locally, then. Thanks for the explanation, though. From my side this can be closed.
